name: Publish Node.js Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating branches and PRs
      pull-requests: write # Needed for creating PRs
      packages: write # Needed for publishing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for version history when using standard-version
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Create bin directory and wrapper script
        run: |
          mkdir -p bin
          echo '#!/usr/bin/env node\n\nimport "../dist/index.js";' > bin/create-node-ts-app.mjs
          chmod +x bin/create-node-ts-app.mjs

      # Version bump on manual trigger and create branch
      - name: Bump version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Create a new branch for version bump
          BRANCH_NAME="release/v${{ github.event.inputs.version }}-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          npm run release:${{ github.event.inputs.version }}
          echo "RELEASE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build package
        run: npm run build

      # Only publish if this is triggered by a tag push
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Create PR for version bump (only on manual workflow)
      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v5
        id: create-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): bump version to ${{ github.event.inputs.version }}'
          title: 'Release: New ${{ github.event.inputs.version }} version'
          body: |
            This PR was automatically created by the GitHub Action workflow.

            Changes:
            - Bumps version to next ${{ github.event.inputs.version }} release
            - Updates CHANGELOG.md with recent changes

            Once merged, a new tag will be created, triggering the publish workflow.
          branch: ${{ env.RELEASE_BRANCH }}
          base: main
          labels: |
            automated pr
            release

      # Auto-approve the PR
      - name: Auto-approve PR
        if: github.event_name == 'workflow_dispatch' && steps.create-pr.outputs.pull-request-number != ''
        run: |
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          # Approve the PR
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve

          echo "✅ PR #${{ steps.create-pr.outputs.pull-request-number }} has been auto-approved"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Auto-merge the PR
      - name: Auto-merge PR
        if: github.event_name == 'workflow_dispatch' && steps.create-pr.outputs.pull-request-number != ''
        run: |
          # Wait a moment for approval to register
          sleep 5

          # Enable auto-merge
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --merge

          echo "🔄 PR #${{ steps.create-pr.outputs.pull-request-number }} has been set to auto-merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
