name: Publish Node.js Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push version changes back to repo
      packages: write # Needed for publishing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for version history when using standard-version
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Create bin directory and wrapper script
        run: |
          mkdir -p bin
          echo '#!/usr/bin/env node\n\nimport "../dist/index.js";' > bin/create-node-ts-app.mjs
          chmod +x bin/create-node-ts-app.mjs

      # Version bump on manual trigger
      - name: Bump version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: npm run release:${{ github.event.inputs.version }}

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Push changes back to repo after publishing (only on manual workflow)
      - name: Push changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git push --follow-tags origin main
